[phases.setup]
nixPkgs = ["nodejs-18_x", "python310", "python310Packages.pip"]

[phases.install]
cmds = [
  "npm ci --legacy-peer-deps",
  "pip3 install -r services/requirements-twitter.txt --no-cache-dir"
]

[phases.build]
cmds = ["npx prisma generate"]

[start]
cmd = "bash workers/start-railway-workers-only.sh"

