[phases.setup]
nixPkgs = ["nodejs_18", "python310", "python310Packages.pip"]

[phases.install]
cmds = [
  "npm ci --legacy-peer-deps",
  "pip3 install -r services/requirements-twitter.txt --no-cache-dir"
]

[phases.build]
cmds = ["npx prisma generate"]

